name: "Delete GitHub App"
on:
  pull_request:
    paths:
      - 'apps.yaml'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform workspace select default || terraform workspace new default
      - run: terraform init
      - name: Detect deleted apps and destroy them
        run: |
          git diff origin/main apps.yaml | grep '^-  - app_name:' | awk '{print $3}' > deleted_apps.txt
          while read -r app; do
            terraform destroy -auto-approve -var="app_name=$app" -var="additional_envs=[]" -var="prd_protection=false"
          done < deleted_apps.txt