name: "Provision GitHub Apps"

on:
  pull_request:
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'
  push:
    branches:
      - main
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python deps
        run: pip install pyyaml

      - name: Generate tfvars files from apps.yaml
        run: |
          mkdir -p terraform/vars
          python3 scripts/generate_tfvars.py

      - name: List generated tfvars files
        run: ls -l terraform/vars/

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          for f in ../terraform/vars/*.auto.tfvars.json; do
            terraform workspace select default || terraform workspace new default
            terraform plan -var-file="$f"
          done

      - name: Terraform Apply on Push to Main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd terraform
          for f in ../terraform/vars/*.auto.tfvars.json; do
            terraform workspace select default || terraform workspace new default
            terraform apply -auto-approve -var-file="$f"
          done
