name: "Provision GitHub Apps"

on:
  pull_request:
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'
  push:
    branches:
      - main
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'

jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python deps
        run: pip install pyyaml

      - name: Generate tfvars files from apps.yaml
        run: |
          mkdir -p terraform/vars
          python3 scripts/generate_tfvars.py

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      - name: Terraform Plan
        run: |
          for f in terraform/vars/*.auto.tfvars.json; do
            cd terraform
            terraform workspace select default || terraform workspace new default
            terraform init
            terraform plan -var-file="../$f"
            cd ..
          done
      
      - name: Terraform Apply (Post-Merge Only)
        if: github.event_name == 'push'
        run: |
          for f in terraform/vars/*.auto.tfvars.json; do
            cd terraform
            terraform workspace select default || terraform workspace new default
            terraform init
            terraform apply -auto-approve -var-file="../$f"
            cd ..
          done

