# ─── .github/workflows/provision.yml ──────────────────────────────────
name: "Provision GitHub Apps"
on:
  pull_request:
    paths:
      - 'apps.yaml'
      - 'terraform/**'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python deps
        run: pip install pyyaml

      - name: Generate tfvars
        run: |
          mkdir -p terraform/vars
          python3 - <<EOF
import yaml, os, json

with open("apps.yaml") as f:
    apps = yaml.safe_load(f)["apps"]

for app in apps:
    path = f"terraform/vars/{app['app_name']}.auto.tfvars.json"
    with open(path, "w") as tfvar_file:
        json.dump(app, tfvar_file)
EOF

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        run: |
          for f in terraform/vars/*.auto.tfvars.json; do
            terraform -chdir=terraform init
            terraform -chdir=terraform plan -var-file="../$f"
          done
