# ─── .github/workflows/provision.yml ──────────────────────────────────
name: "Provision GitHub Apps"

on:
  pull_request:
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'
      - '*'
  push:
    branches:
      - main
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python deps
        run: pip install pyyaml

      - name: Generate tfvars files
        run: |
          mkdir -p terraform/vars
          python3 scripts/generate_tfvars.py

      - name: Debug List contents of terraformvars
        run: |
          ls -l terraform/vars
          cat terraform/vars/*.auto.tfvars.json

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        run: |
          cd terraform
          terraform init
          for f in ../terraform/vars/*.auto.tfvars.json; do
            echo "Planning with $f"
            terraform plan -var-file="$f"
          done
