# ─── .github/workflows/provision.yml ──────────────────────────────────
name: "Provision GitHub Apps"

on:
  pull_request:
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'
  push:
    branches:
      - main
    paths:
      - 'apps.yaml'
      - 'terraform/**'
      - 'scripts/generate_tfvars.py'

jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Python deps
        run: pip install pyyaml

      - name: Generate tfvars files from apps.yaml
        run: |
          mkdir -p terraform/vars
          python3 scripts/generate_tfvars.py

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        run: |
          cd terraform
          terraform init
          for f in ../terraform/vars/*.auto.tfvars.json; do
            terraform plan -var-file="$f"
          done

      # Terraform Apply is intentionally skipped because the workspace is VCS-connected.
      # Terraform Cloud will handle apply after merge automatically.
